training_pipeline_config:
  pipeline_name: pneumonia
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: paultimothymooney/chest-xray-pneumonia
  tgz_download_dir: tgz_data
  ingested_dir : ingested_data

model_trainer_config :
  trained_model_dir : trained_model
  model_file_name : CNN.h5
  model_config_dir : yaml_config
  model_config_file_name : model.yaml

model_pusher_config :
  saved_model_dir : saved_model